# Orbit Analyzer Configuration
# Place this file at the root of your project as .orlint.toml

# Analyzer settings
[analyzer]
# Enabled linting rules (if empty, all rules are enabled except disabled ones)
enabled_rules = [
  "non-empty-template",
  "public-function", 
  "component-naming",
  "prop-type-required",
  "state-variable-usage"
]

# Disabled linting rules
disabled_rules = []

# Report format: "text", "json", "html"
report_format = "text"

# Output file (if not specified, output goes to stdout)
# output_file = "orlint-report.html"

# Run analysis in parallel for better performance on large codebases
parallel = true

# Fail on warnings as well as errors
fail_on_warnings = false

# Rules configurations
[rules.component-naming]
# Pattern is a regular expression for component names
pattern = "^[A-Z][a-zA-Z0-9]*$"  # PascalCase

# Rule severity overrides
[rule_severity]
"non-empty-template" = "Error"
"public-function" = "Info"
"component-naming" = "Warning"
"prop-type-required" = "Error"
"state-variable-usage" = "Warning"
"renderer-compatibility" = "Error"

# Renderer-specific analysis settings
[renderer_analysis]
# Enable renderer-specific analysis
enabled = true

# Default renderer to check compatibility with ("auto", "skia", "webgpu")
default_renderer = "skia"

# Check renderer metadata in components
check_renderer_metadata = true

# Reporter configuration
[reporter]
# Minimum severity level to report ("Error", "Warning", "Info")
min_severity = "Warning"
