name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    uses: orbitrs/orbit-workflows/.github/workflows/reusable/rust-ci.yml@main
    with:
      cross-platform: true
